spring.application.name=Blog
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=tarakki
spring.datasource.password=tarakki
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=WARN
server.port=7070
logging.banner.enabled=FALSE